### ISSUE TITLE
[BUG] Can't write "notes" on users who left

### ISSUE THREAD

**Issue by ghost** [stem-discord/stembot-issues#16]
# version
* 1.0.0
# branch
* dev-1

latest commit hash
> 4fcca01c

Example of what currently happens: https://discord.com/channels/493173110799859713/666989960884387891/773419445497495572

**Expected behavior**
Being able to use the !note {user} {content} command on users who are no longer in the server.

**Comment by nopeless** [comment]
this should be a simple fix
ill release a patch soon

**Comment by nopeless** [comment]
we should just give people who send message but dont have role in cache the role
