### ISSUE TITLE
[BUG] Points don't work

### ISSUE THREAD

**Issue by shivzy2002** [stem-discord/stembot-issues#17]
# version
* 1.0.0
# branch
* dev-1

latest commit hash
> 4fcca01c

The points current;y do no work. When they did, it used to be that people would get a point after sending a certain amount of messages and 10 points for a bump (the bump points have to go because of disboard tos), but the others could be brought back in. Also, maybe doing !daily can also give 5ish points, that would encourage more activity as well. And since they have not been working for a long time, and the og people have a huge advantage, how about a whole point reset? (this is me just jotting down my ideas, we could discuss this more to make it more concrete if you'd like)

**Expected behavior**
Points go up with user activity + some other event like the !daily

**Comment by nopeless** [comment]
ill see whats happening under the hood

**Comment by nopeless** [comment]
fixed in v1.0.2
