### ISSUE TITLE
[BUG] statistics-scoreboard shows star instead on an arrow

### ISSUE THREAD

**Issue by arshsverma** [stem-discord/stembot-issues#18]
In statistics-scoreboard, in the scoreboard there is a star next to the name of Harsh instead of an arrow which is normally what should be there. that star is seen when a specific person sends the !top command, but it shouldn't be there on the scoreboard.

Expected behavior
there should be an arrow there.

![image](https://user-images.githubusercontent.com/47853748/104834029-cf50a280-58c2-11eb-836a-02ad8f2fa03a.png)

**Comment by nopeless** [comment]
i dont think its a bug

**Comment by nopeless** [comment]
@arshsverma
