### ISSUE TITLE
[BUG] !version doesn't work

### ISSUE THREAD

**Issue by arshsverma** [stem-discord/stembot-issues#19]
When trying to run `!version` the bot says that permissions are missing

**Expected behavior**
It should work even without any permissions

**Screenshots**
![image](https://user-images.githubusercontent.com/47853748/104834203-ec39a580-58c3-11eb-900e-9b83441c3bf8.png)

**Comment by nopeless** [comment]
will fix it

**Comment by nopeless** [comment]
fixed
