### ISSUE TITLE
[BUG] !purge for mods does not work for their sole messages

### ISSUE THREAD

**Issue by nopmademedoit** [stem-discord/stembot-issues#20]
mods cannot purge their own messages

they can purge their messages IF AND ONLY IF someone else types in between their messages

see example for proof they cant

![image](https://user-images.githubusercontent.com/76517978/104892676-913ca700-59c6-11eb-8121-0e651418d5ea.png)

mods should be able to do this

**Comment by nopeless** [comment]
thats a weird bug, ill see whats happening here. 
but i have other stuff so maybe rem will tackle this

**Comment by nopeless** [comment]
the purge checks if the user is self i think
i think this is indended behavior

**Comment by nopeless** [comment]
@nopmademedoit

**Comment by nopeless** [comment]
closing because no response
