### ISSUE TITLE
Ban Appeal Server Invite

### ISSUE THREAD

**Issue by shivzy2002** [stem-discord/stembot-issues#24]
"can someone add a GitHub issue for me so that it fits my workflow to set the ban appeal server invite" - Nope

I think it means the -invite flag at the end of the ban command but I'm not entirely sure thus quoting above^

**Comment by nopeless** [comment]
yeah its invalid atm ill add the invite flag in a moment

**Comment by nopeless** [comment]
fixed this in i think 1.0.5
