### ISSUE TITLE
[BUG] Smute doesn't work if user has access to #development

### ISSUE THREAD

**Issue by Shlurp** [stem-discord/stembot-issues#26]
**Please Include `!version` Below**
1.0.4

**To Reproduce**
1. Use `!smute` on any channel
2. You'll see you have access to the `#development` channel
3. That's it really. The `!sunmute` command works in the `#development` channel too.

* What roles do you think cause this behavior? The `@git-contributer` role
* What command/action did you do? `!smute`
* Where did you do this? `#commands`
* When did you do this? (helps when tracing logs. use UTC) 8:09 AM, January 28 

**Expected behavior**
I would use `!smute`, and only have access to the `#study` mute channel, not the `#development` channel.

**Comment by nopeless** [comment]
this isnt a stem bot issue
