### ISSUE TITLE
[BUG] No duplicate VC channels for code-help

### ISSUE THREAD

**Issue by Shlurp** [stem-discord/stembot-issues#27]
# BEFORE YOU SUBMIT AN ISSUE, PLEASE CHECK OPEN/CLOSED ISSUES FOR DUPLICATES
you may delete the line above after checking

**Please Include `!version` Below**
1.0.4

**To Reproduce**
1. Go on `#coding help`
2. See no `#coding help [1]`

* What roles do you think cause this behavior? All of them, I'd assume
* What command/action did you do? I joined a VC (rather, I noticed someone had)
* Where did you do this? `#coding help`
* When did you do this? (helps when tracing logs. use UTC) 23:40

**Expected behavior**
That joining `#coding help` would create a duplicate channel `#coding help [1]`

**Screenshots**
![image](https://user-images.githubusercontent.com/59257511/106212357-19932700-61d3-11eb-8006-1dce48d34d40.png)

**Comment by nopeless** [comment]
briefly fixed
