### ISSUE TITLE
[BUG] Pinging mod/admin right after pinging helper triggers cooldown message

### ISSUE THREAD

**Issue by MrEnginerdy** [stem-discord/stembot-issues#30]
Low priority because mods/admins are properly pinged, and this is a corner case. It's just a confusing message to the one pinging.

# version
* 1.0.7
# branch
* dev

latest commit hash
> 8d8b6ee9

**To Reproduce**
1. Ping Helper, wait 1 minute for the ping to go through (don't cancel it while waiting)
2. When the ping goes through, "So-and-so needs help", ping Moderator or Administrator
3. STEM bot will send a cooldown message (see screenshots at the bottom)

* What roles do you think cause this behavior?
Someone with Valued/Supporter caused it. Unclear which roles cause it or if it would happen to anyone
* What command/action did you do?
@Helper->Math quickly followed by @Moderator or @Administrator
* Where did you do this?
general-math help channel
* When did you do this? (helps when tracing logs. use UTC)
2021-02-15 at 01:45 UTC

**Expected behavior**
Pinging @moderator or @administrator from any channel notifies those with the appropriate role without triggering the cooldown message from the bot

**Screenshots**
https://discord.com/channels/493173110799859713/597096637122347027/810688299462295602
https://discord.com/channels/493173110799859713/688023733587411028/810712924884566058

**Comment by nopeless** [comment]
@MrEnginerdy fixed in 1.0.8 but im not sure if its totally fixed it
