### ISSUE TITLE
[BUG] !check shows undefined for notes

### ISSUE THREAD

**Issue by Remceau** [stem-discord/stembot-issues#5]
When a user doesn't have any notes the result of !check shows "undefined" instead of a more user friendly message.

**Please Include `!version` Below**
version: 1.0.0
branch: dev
commit hash: da3bbe5d

**To Reproduce**
* Use !check on a member which doesn't have any past notes.

**Expected behavior**
A nice message is shown like "No notes found"

**Current Behavior**
The field just shows "undefined"

**Comment by Remceau** [comment]
Will try to fix it myself since it is pretty basic

**Comment by nopeless** [comment]
probably a stupid bug created when fixing god's array of `var`
