### ISSUE TITLE
[BUG] Color roles not automatically removed

### ISSUE THREAD

**Issue by Remceau** [stem-discord/stembot-issues#6]
The color roles of boosters aren't always automatically removed. For one it may be caused by the fact that he got the role without the automated system, but the other person i have found this bug with started boosting after the new system was in place. The specific users i have found with regards to this bug are Krm#0004 and pibbles#5764.

**Please Include `!version` Below**
Version: 1.0.0
Branch: dev
Commit: da3bbe5d

**Comment by incaw** [comment]
People without the booster role won't have their color removed automatically, instead the bot will send a message notifying that a supporter has lost their role and show a list of everyone they were gifting color to.

**Comment by incaw** [comment]
Fixed in version * 1.1.5
